### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by m4rc1e** [Typedesigners/Anta-Regular#7]
In order for the fonts to generate, we need to create a new release. Read the steps here:

> Google Fonts uses Github Releases to manage font families. If you feel your font project has hit a milestone, you must create a new release for it. In order to do this, go to the releases page and hit the "Draft a new release button". You must provide a tag number and title which can only be a decimal number e.g 0.100, 1.000 etc. For the body text, mention what has changed since the last release. Once you are done, hit the "Publish release" button. Here is an example which fulfills the requirements, https://github.com/m4rc1e/test-ufr-family/releases/tag/2.019. For more info regarding Github release, please see the official Github Release [documentation](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository). Please note that Github Actions must be able to build the fonts before you can make a release. Once you have made a release, the fonts and tests assets will be attached to the release automatically. This may take a while since the fonts and tests will be built from scratch so please be patient.

**Comment by Typedesigners** [comment]
Thanks for the information. I have published Anta Release on Github.

**Comment by Typedesigners** [comment]
Hello Marc, the release of Anta is ready, only the fonts are missing. Can you please make the Anta fonts with Google Fonts Tools now?

**Comment by m4rc1e** [comment]
Hello,

Thanks and yes you're right. Would you mind assigning me as an admin to this repo? I can then fix it without needing you to merge things. This should be in settings somewhere. Apologies for the inconvenience.

**Comment by m4rc1e** [comment]
Thank you for the invite. I'll get this repo working. Apologies for the delay.

**Comment by Typedesigners** [comment]
I have just done the following:
"m4rc1e has been added as a collaborator on the repository." 
Did they mean that?

**Comment by m4rc1e** [comment]
That's correct thank you!

**Comment by m4rc1e** [comment]
I need to access the settings for this repo. Could you go https://github.com/Typedesigners/Anta-Regular/settings/access and change me to an admin please?

**Comment by Typedesigners** [comment]
I have already added you as a collaborator. I don't see any other setting here that makes you an admin.
![Screenshot 2024-01-25 110923](https://github.com/Typedesigners/Anta-Regular/assets/124695645/8c496f48-bd61-43fe-ac68-a1f868dfc2a6)

**Comment by Typedesigners** [comment]
If you want me to make further settings so that you can create the Anta fonts with gftools, please let me know.

**Comment by Typedesigners** [comment]
Hello Marc, I have just made a new Release of Anta. Version 1.001. It is the same as before, only in the Source code (zip) the fonts folder has been added. So the release is complete. Is there a date when Anta can be downloaded from Google Fonts?
